approvals:
  pattern: "^(:\\+1:|👍)" # must start with thumbs up
  ignore: none           # allow pr-opener and last committer to ack PRs
  groups:
    zalando:
      minimum: 2
      from:
        orgs:
          - "zalando"
    # lenalebt is required approver on every PR
    seniors:
      minimum: 1
      from:
        users:
          - musiKk
          - hardvain

X-Zalando-Team: "kohle"
X-Zalando-Type: code
